/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.m.routing.RouteMatchedHandler");jQuery.sap.require("sap.ui.base.Object");jQuery.sap.require("sap.ui.core.routing.Router");jQuery.sap.require("sap.ui.core.routing.History");jQuery.sap.require("sap.m.InstanceManager");jQuery.sap.require("sap.m.SplitContainer");jQuery.sap.require("sap.m.NavContainer");sap.ui.base.Object.extend("sap.m.routing.RouteMatchedHandler",{constructor:function(r,c){this._aQueue=[];if(c===undefined){this._bCloseDialogs=true}else{this._bCloseDialogs=!!c}r.attachRouteMatched(this._onHandleRouteMatched,this);r.attachRoutePatternMatched(this._handleRoutePatternMatched,this);this._oRouter=r}});
sap.m.routing.RouteMatchedHandler.prototype.destroy=function(){this._oRouter.detachRouteMatched(this._onHandleRouteMatched,this);this._oRouter.detachRoutePatternMatched(this._handleRoutePatternMatched,this);this._oRouter=null;return this};
sap.m.routing.RouteMatchedHandler.prototype.setCloseDialogs=function(c){this._bCloseDialogs=!!c;return this};
sap.m.routing.RouteMatchedHandler.prototype.getCloseDialogs=function(){return this._bCloseDialogs};
sap.m.routing.RouteMatchedHandler.prototype._handleRoutePatternMatched=function(e){var t=+e.getParameter("config").viewLevel,h=sap.ui.core.routing.History.getInstance(),b,p,n,r=this._createResultingNavigations();if(isNaN(t)||isNaN(this._iCurrentViewLevel)||t===this._iCurrentViewLevel){b=h.getDirection()==="Backwards"}else{b=t<this._iCurrentViewLevel}while(r.length){this._handleRouteMatched(r.shift().oParams,b)}this._iCurrentViewLevel=t};
sap.m.routing.RouteMatchedHandler.prototype._onHandleRouteMatched=function(e){this._aQueue.push({oTargetControl:e.getParameter("targetControl"),oArguments:e.getParameter("arguments"),sTransition:e.getParameter("config").transition,oTransitionParameters:e.getParameter("config").transitionParameters,oView:e.getParameter("view")})};
sap.m.routing.RouteMatchedHandler.prototype._createResultingNavigations=function(){var i,f,c,C,o,r=[],v,R;while(this._aQueue.length){f=false;c=this._aQueue.shift();C=c.oTargetControl;o={oContainer:C,oParams:c};v=c.oView;if(!(C instanceof sap.m.NavContainer||C instanceof sap.m.SplitContainer)||!v){continue}for(i=0;i<r.length;i++){R=r[i];if(R.oContainer!==C){continue}if(C instanceof sap.m.NavContainer||sap.ui.Device.system.phone){r.splice(i,1);r.push(o);f=true;break}o.bIsMasterPage=!!C.getMasterPage(v.getId());if(R.bIsMasterPage===o.bIsMasterPage){r.splice(i,1);r.push(o);f=true;break}else{continue}}if(C instanceof sap.m.SplitContainer&&!sap.ui.Device.system.phone){o.bIsMasterPage=!!C.getMasterPage(v.getId())}if(!f){r.push(o)}}return r};
sap.m.routing.RouteMatchedHandler.prototype._handleRouteMatched=function(p,b,t){var t=p.oTargetControl,v,n,P,a=p.oArguments,T=p.sTransition,o=p.oTransitionParameters;this._closeDialogs();v=p.oView.getId();n=t instanceof sap.m.SplitContainer&&!!t.getMasterPage(v);if(t.getCurrentPage(n).getId()===v){jQuery.sap.log.info("navigation to view with id: "+v+" is skipped since it already is displayed by its targetControl");return}jQuery.sap.log.info("navigation to view with id: "+v+" the targetControl is "+t.getId()+" backwards is "+b);if(b){P=t.getPreviousPage(n);if(!P||P.getId()!==v){t.insertPreviousPage(v,T,a)}t.backToPage(v,a,o)}else{t.to(v,T,a,o)}};
sap.m.routing.RouteMatchedHandler.prototype._closeDialogs=function(){if(!this._bCloseDialogs){return}if(sap.m.InstanceManager.hasOpenPopover()){sap.m.InstanceManager.closeAllPopovers()}if(sap.m.InstanceManager.hasOpenDialog()){sap.m.InstanceManager.closeAllDialogs()}}
